<?php 
include 'core/init.php';
include 'includes/overall/overallheader.php'; 
?>

<style>
body {
		 background-image:url(images/ktyxhj_1016.jpg);
}
</style>

	<h1>Gallery</h1>
	<p>slide show</p>


  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="50" height="325">
    <param name="flash_component" value="ImageViewer.swc" />
    <param name="movie" value="images/playgrounds/slideshow.swf" />
    <param name="quality" value="high" />
    <param name="FlashVars" value="flashlet={imageLinkTarget:'_blank',captionFont:'Verdana',titleFont:'Verdana',showControls:false,frameShow:false,slideDelay:5,captionSize:10,captionColor:#333333,titleSize:10,transitionsType:'Random',titleColor:#333333,slideAutoPlay:true,imageURLs:['images/playgrounds/images.jpeg','images/playgrounds/images-1.jpeg','images/playgrounds/images-2.jpeg','images/playgrounds/images-3.jpeg','images/playgrounds/images-4.jpeg','images/playgrounds/images-5.jpeg','images/playgrounds/images-6.jpeg','images/playgrounds/images-7.jpeg','images/playgrounds/images-8.jpeg','images/playgrounds/images-9.jpeg','images/playgrounds/images-10.jpeg','images/playgrounds/images-11.jpeg','images/playgrounds/images-12.jpeg'],slideLoop:false,frameThickness:2,imageLinks:['http://macromedia.com/','http://macromedia.com/','http://macromedia.com/'],frameColor:#333333,bgColor:#FFFFFF,imageCaptions:[]}" />
    <embed src="images/playgrounds/slideshow.swf" quality="high" flashvars="flashlet={imageLinkTarget:'_blank',captionFont:'Verdana',titleFont:'Verdana',showControls:false,frameShow:false,slideDelay:5,captionSize:10,captionColor:#333333,titleSize:10,transitionsType:'Random',titleColor:#333333,slideAutoPlay:true,imageURLs:['images/playgrounds/images.jpeg','images/playgrounds/images-1.jpeg','images/playgrounds/images-2.jpeg','images/playgrounds/images-3.jpeg','images/playgrounds/images-4.jpeg','images/playgrounds/images-5.jpeg','images/playgrounds/images-6.jpeg','images/playgrounds/images-7.jpeg','images/playgrounds/images-8.jpeg','images/playgrounds/images-9.jpeg','images/playgrounds/images-10.jpeg','images/playgrounds/images-11.jpeg','images/playgrounds/images-12.jpeg'],slideLoop:false,frameThickness:2,imageLinks:['http://macromedia.com/','http://macromedia.com/','http://macromedia.com/'],frameColor:#333333,bgColor:#FFFFFF,imageCaptions:[]}" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="400" height="325"> </embed>
  </object>
  
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="200" height="325">
    <param name="flash_component" value="ImageViewer.swc" />
    <param name="movie" value="images/times/slideshow2.swf" />
    <param name="quality" value="high" />
    <param name="FlashVars" value="flashlet={imageLinkTarget:'_blank',captionFont:'Verdana',titleFont:'Verdana',showControls:false,frameShow:false,slideDelay:5,captionSize:10,captionColor:#333333,titleSize:10,transitionsType:'Random',titleColor:#333333,slideAutoPlay:true,imageURLs:['images/times/images (2).jpeg','images/times/images-1 (2).jpeg','images/times/images-2.jpeg','images/times/images-3.jpeg','images/times/images-4.jpeg','images/times/images-5.jpeg','images/times/images-6.jpeg','images/times/images-7.jpeg','images/times/images-8.jpeg','images/times/images-9.jpeg','images/times/images-10.jpeg','images/times/images-11.jpeg','images/times/images-12.jpeg','images/times/images-13.jpeg','images/times/images-14.jpeg','images/times/images-15.jpeg','images/times/images-16.jpeg','images/times/images-17.jpeg','images/times/images-18.jpeg','images/times/images-19.jpeg','images/times/images-20.jpeg','images/times/images-21.jpeg','images/times/images-22.jpeg','images/times/images-23.jpeg','images/times/images-24.jpeg','images/times/images-25.jpeg','images/times/images-27.jpeg','images/times/images-26.jpeg','images/times/images-28.jpeg','images/times/images-29.jpeg','images/times/images-30.jpeg','images/times/images-31.jpeg','images/times/images-32.jpeg','images/times/images-34.jpeg','images/times/images-33.jpeg','images/times/images-34.jpeg','images/times/images-35.jpeg','images/times/images-36.jpeg','images/times/images-37.jpeg','images/times/images-38.jpeg','images/times/images-39.jpeg','images/times/images-40.jpeg','images/times/images-41.jpeg'],slideLoop:true,frameThickness:2,imageLinks:['http://macromedia.com/','http://macromedia.com/','http://macromedia.com/'],frameColor:#333333,bgColor:#FFFFFF,imageCaptions:[]}" />
    <embed src="images/times/slideshow2.swf" quality="high" flashvars="flashlet={imageLinkTarget:'_blank',captionFont:'Verdana',titleFont:'Verdana',showControls:false,frameShow:false,slideDelay:5,captionSize:10,captionColor:#333333,titleSize:10,transitionsType:'Random',titleColor:#333333,slideAutoPlay:true,imageURLs:['images/times/images (2).jpeg','images/times/images-1 (2).jpeg','images/times/images-2.jpeg','images/times/images-3.jpeg','images/times/images-4.jpeg','images/times/images-5.jpeg','images/times/images-6.jpeg','images/times/images-7.jpeg','images/times/images-8.jpeg','images/times/images-9.jpeg','images/times/images-10.jpeg','images/times/images-11.jpeg','images/times/images-12.jpeg','images/times/images-13.jpeg','images/times/images-14.jpeg','images/times/images-15.jpeg','images/times/images-16.jpeg','images/times/images-17.jpeg','images/times/images-18.jpeg','images/times/images-19.jpeg','images/times/images-20.jpeg','images/times/images-21.jpeg','images/times/images-22.jpeg','images/times/images-23.jpeg','images/times/images-24.jpeg','images/times/images-25.jpeg','images/times/images-27.jpeg','images/times/images-26.jpeg','images/times/images-28.jpeg','images/times/images-29.jpeg','images/times/images-30.jpeg','images/times/images-31.jpeg','images/times/images-32.jpeg','images/times/images-34.jpeg','images/times/images-33.jpeg','images/times/images-34.jpeg','images/times/images-35.jpeg','images/times/images-36.jpeg','images/times/images-37.jpeg','images/times/images-38.jpeg','images/times/images-39.jpeg','images/times/images-40.jpeg','images/times/images-41.jpeg'],slideLoop:true,frameThickness:2,imageLinks:['http://macromedia.com/','http://macromedia.com/','http://macromedia.com/'],frameColor:#333333,bgColor:#FFFFFF,imageCaptions:[]}" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="400" height="325"> </embed>
  </object>
	
<?php include 'includes/overall/overallfooter.php'; ?>